#-------------------------------
# General Site Settings
title: vojay
logo:
description: Volker Janz - Thoughts, stories and ideas from a Data Engineer, Software Developer, Passionate Speaker, Gym Enthusiast and Adventurer
domain: vojay-dev.github.io
url: https://vojay-dev.github.io
baseurl: ""


#-------------------------------
# Author Settings
author:
  name: Volker Janz
  avatar: '/images/avatar.jpg'


#-------------------------------
# Hero Settings
hero:
  title: Volker Janz
  description: Thoughts, stories and ideas from a Data Engineer, Software Developer, Passionate Speaker, Gym Enthusiast and Adventurer
  image: '/images/header/home.jpg'


#-------------------------------
# Contact Settings
contact:
  email: volker@janz.sh
  description: I am always looking for challenges and opportunities to share experiences and learn from others. Feel free to reach out to me.


#-------------------------------
# Footer section
# Icons overview https://ionicons.com/v4/
social:
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/vjanz/"}
- {icon: "ion-logo-instagram", link: "https://www.instagram.com/vojay.de"}
- {icon: "ion-logo-github", link: "https://github.com/vojay-dev"}


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: vojay


#-------------------------------
# Google Analytics
google-analytics: G-Y1D1YZJQ7T


#-------------------------------
# Newsletter
mailchimp: # To enable the mailchimp form, use value 'enable'
mailchimp-identifier:


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-feed
  - jekyll-seo-tag

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
